-- ============================================================
-- TOPICS
-- ============================================================
INSERT INTO public.topics (subject_id, name, slug, description) VALUES
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 1', 'chemistry-class-11-ch-1', 'NCERT PDF for Chemistry Class 11 - Chapter 1'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 2', 'chemistry-class-11-ch-2', 'NCERT PDF for Chemistry Class 11 - Chapter 2'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 3', 'chemistry-class-11-ch-3', 'NCERT PDF for Chemistry Class 11 - Chapter 3'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 4', 'chemistry-class-11-ch-4', 'NCERT PDF for Chemistry Class 11 - Chapter 4'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 5', 'chemistry-class-11-ch-5', 'NCERT PDF for Chemistry Class 11 - Chapter 5'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 6', 'chemistry-class-11-ch-6', 'NCERT PDF for Chemistry Class 11 - Chapter 6'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 7', 'chemistry-class-11-ch-7', 'NCERT PDF for Chemistry Class 11 - Chapter 7'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 8', 'chemistry-class-11-ch-8', 'NCERT PDF for Chemistry Class 11 - Chapter 8'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 11 - Chapter 9', 'chemistry-class-11-ch-9', 'NCERT PDF for Chemistry Class 11 - Chapter 9'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 1', 'chemistry-class-12-ch-1', 'NCERT PDF for Chemistry Class 12 - Chapter 1'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 2', 'chemistry-class-12-ch-2', 'NCERT PDF for Chemistry Class 12 - Chapter 2'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 3', 'chemistry-class-12-ch-3', 'NCERT PDF for Chemistry Class 12 - Chapter 3'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 4', 'chemistry-class-12-ch-4', 'NCERT PDF for Chemistry Class 12 - Chapter 4'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 5', 'chemistry-class-12-ch-5', 'NCERT PDF for Chemistry Class 12 - Chapter 5'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 6', 'chemistry-class-12-ch-6', 'NCERT PDF for Chemistry Class 12 - Chapter 6'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 7', 'chemistry-class-12-ch-7', 'NCERT PDF for Chemistry Class 12 - Chapter 7'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 8', 'chemistry-class-12-ch-8', 'NCERT PDF for Chemistry Class 12 - Chapter 8'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 9', 'chemistry-class-12-ch-9', 'NCERT PDF for Chemistry Class 12 - Chapter 9'),
  ((SELECT id FROM public.subjects WHERE slug = 'chemistry'), 'Chemistry Class 12 - Chapter 10', 'chemistry-class-12-ch-10', 'NCERT PDF for Chemistry Class 12 - Chapter 10'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 1', 'physics-class-11-ch-1', 'NCERT PDF for Physics Class 11 - Chapter 1'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 2', 'physics-class-11-ch-2', 'NCERT PDF for Physics Class 11 - Chapter 2'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 3', 'physics-class-11-ch-3', 'NCERT PDF for Physics Class 11 - Chapter 3'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 4', 'physics-class-11-ch-4', 'NCERT PDF for Physics Class 11 - Chapter 4'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 5', 'physics-class-11-ch-5', 'NCERT PDF for Physics Class 11 - Chapter 5'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 6', 'physics-class-11-ch-6', 'NCERT PDF for Physics Class 11 - Chapter 6'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 7', 'physics-class-11-ch-7', 'NCERT PDF for Physics Class 11 - Chapter 7'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 8', 'physics-class-11-ch-8', 'NCERT PDF for Physics Class 11 - Chapter 8'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 9', 'physics-class-11-ch-9', 'NCERT PDF for Physics Class 11 - Chapter 9'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 10', 'physics-class-11-ch-10', 'NCERT PDF for Physics Class 11 - Chapter 10'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 11', 'physics-class-11-ch-11', 'NCERT PDF for Physics Class 11 - Chapter 11'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 12', 'physics-class-11-ch-12', 'NCERT PDF for Physics Class 11 - Chapter 12'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 13', 'physics-class-11-ch-13', 'NCERT PDF for Physics Class 11 - Chapter 13'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 11 - Chapter 14', 'physics-class-11-ch-14', 'NCERT PDF for Physics Class 11 - Chapter 14'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 1', 'physics-class-12-ch-1', 'NCERT PDF for Physics Class 12 - Chapter 1'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 2', 'physics-class-12-ch-2', 'NCERT PDF for Physics Class 12 - Chapter 2'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 3', 'physics-class-12-ch-3', 'NCERT PDF for Physics Class 12 - Chapter 3'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 4', 'physics-class-12-ch-4', 'NCERT PDF for Physics Class 12 - Chapter 4'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 5', 'physics-class-12-ch-5', 'NCERT PDF for Physics Class 12 - Chapter 5'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 6', 'physics-class-12-ch-6', 'NCERT PDF for Physics Class 12 - Chapter 6'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 7', 'physics-class-12-ch-7', 'NCERT PDF for Physics Class 12 - Chapter 7'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 8', 'physics-class-12-ch-8', 'NCERT PDF for Physics Class 12 - Chapter 8'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 9', 'physics-class-12-ch-9', 'NCERT PDF for Physics Class 12 - Chapter 9'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 10', 'physics-class-12-ch-10', 'NCERT PDF for Physics Class 12 - Chapter 10'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 11', 'physics-class-12-ch-11', 'NCERT PDF for Physics Class 12 - Chapter 11'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 12', 'physics-class-12-ch-12', 'NCERT PDF for Physics Class 12 - Chapter 12'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 13', 'physics-class-12-ch-13', 'NCERT PDF for Physics Class 12 - Chapter 13'),
  ((SELECT id FROM public.subjects WHERE slug = 'physics'), 'Physics Class 12 - Chapter 14', 'physics-class-12-ch-14', 'NCERT PDF for Physics Class 12 - Chapter 14'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 1', 'biology-class-11-ch-1', 'NCERT PDF for Biology Class 11 - Chapter 1'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 2', 'biology-class-11-ch-2', 'NCERT PDF for Biology Class 11 - Chapter 2'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 3', 'biology-class-11-ch-3', 'NCERT PDF for Biology Class 11 - Chapter 3'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 4', 'biology-class-11-ch-4', 'NCERT PDF for Biology Class 11 - Chapter 4'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 5', 'biology-class-11-ch-5', 'NCERT PDF for Biology Class 11 - Chapter 5'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 6', 'biology-class-11-ch-6', 'NCERT PDF for Biology Class 11 - Chapter 6'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 7', 'biology-class-11-ch-7', 'NCERT PDF for Biology Class 11 - Chapter 7'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 8', 'biology-class-11-ch-8', 'NCERT PDF for Biology Class 11 - Chapter 8'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 9', 'biology-class-11-ch-9', 'NCERT PDF for Biology Class 11 - Chapter 9'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 10', 'biology-class-11-ch-10', 'NCERT PDF for Biology Class 11 - Chapter 10'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 11', 'biology-class-11-ch-11', 'NCERT PDF for Biology Class 11 - Chapter 11'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 12', 'biology-class-11-ch-12', 'NCERT PDF for Biology Class 11 - Chapter 12'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 13', 'biology-class-11-ch-13', 'NCERT PDF for Biology Class 11 - Chapter 13'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 14', 'biology-class-11-ch-14', 'NCERT PDF for Biology Class 11 - Chapter 14'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 15', 'biology-class-11-ch-15', 'NCERT PDF for Biology Class 11 - Chapter 15'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 16', 'biology-class-11-ch-16', 'NCERT PDF for Biology Class 11 - Chapter 16'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 17', 'biology-class-11-ch-17', 'NCERT PDF for Biology Class 11 - Chapter 17'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 18', 'biology-class-11-ch-18', 'NCERT PDF for Biology Class 11 - Chapter 18'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 11 - Chapter 19', 'biology-class-11-ch-19', 'NCERT PDF for Biology Class 11 - Chapter 19'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 1', 'biology-class-12-ch-1', 'NCERT PDF for Biology Class 12 - Chapter 1'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 2', 'biology-class-12-ch-2', 'NCERT PDF for Biology Class 12 - Chapter 2'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 3', 'biology-class-12-ch-3', 'NCERT PDF for Biology Class 12 - Chapter 3'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 4', 'biology-class-12-ch-4', 'NCERT PDF for Biology Class 12 - Chapter 4'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 5', 'biology-class-12-ch-5', 'NCERT PDF for Biology Class 12 - Chapter 5'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 6', 'biology-class-12-ch-6', 'NCERT PDF for Biology Class 12 - Chapter 6'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 7', 'biology-class-12-ch-7', 'NCERT PDF for Biology Class 12 - Chapter 7'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 8', 'biology-class-12-ch-8', 'NCERT PDF for Biology Class 12 - Chapter 8'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 9', 'biology-class-12-ch-9', 'NCERT PDF for Biology Class 12 - Chapter 9'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 10', 'biology-class-12-ch-10', 'NCERT PDF for Biology Class 12 - Chapter 10'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 11', 'biology-class-12-ch-11', 'NCERT PDF for Biology Class 12 - Chapter 11'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 12', 'biology-class-12-ch-12', 'NCERT PDF for Biology Class 12 - Chapter 12'),
  ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'Biology Class 12 - Chapter 13', 'biology-class-12-ch-13', 'NCERT PDF for Biology Class 12 - Chapter 13')
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- NCERT CONTENT (PDFs)
-- ============================================================
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES
(1, 'Chemistry Class 11 - Chapter 1 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech101.pdf'),
(2, 'Chemistry Class 11 - Chapter 2 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech102.pdf'),
(3, 'Chemistry Class 11 - Chapter 3 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech103.pdf'),
(4, 'Chemistry Class 11 - Chapter 4 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech104.pdf'),
(5, 'Chemistry Class 11 - Chapter 5 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech105.pdf'),
(6, 'Chemistry Class 11 - Chapter 6 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech106.pdf'),
(7, 'Chemistry Class 11 - Chapter 7 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech201.pdf'),
(8, 'Chemistry Class 11 - Chapter 8 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech202.pdf'),
(9, 'Chemistry Class 11 - Chapter 9 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_11/kech203.pdf'),
(10, 'Chemistry Class 12 - Chapter 1 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech101.pdf'),
(11, 'Chemistry Class 12 - Chapter 2 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech102.pdf'),
(12, 'Chemistry Class 12 - Chapter 3 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech103.pdf'),
(13, 'Chemistry Class 12 - Chapter 4 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech104.pdf'),
(14, 'Chemistry Class 12 - Chapter 5 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech105.pdf'),
(15, 'Chemistry Class 12 - Chapter 6 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech201.pdf'),
(16, 'Chemistry Class 12 - Chapter 7 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech202.pdf'),
(17, 'Chemistry Class 12 - Chapter 8 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech203.pdf'),
(18, 'Chemistry Class 12 - Chapter 9 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech204.pdf'),
(19, 'Chemistry Class 12 - Chapter 10 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Chemistry/Class_12/lech205.pdf'),
(20, 'Physics Class 11 - Chapter 1 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph101.pdf'),
(21, 'Physics Class 11 - Chapter 2 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph102.pdf'),
(22, 'Physics Class 11 - Chapter 3 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph103.pdf'),
(23, 'Physics Class 11 - Chapter 4 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph104.pdf'),
(24, 'Physics Class 11 - Chapter 5 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph105.pdf'),
(25, 'Physics Class 11 - Chapter 6 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph106.pdf'),
(26, 'Physics Class 11 - Chapter 7 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph107.pdf'),
(27, 'Physics Class 11 - Chapter 8 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph201.pdf'),
(28, 'Physics Class 11 - Chapter 9 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph202.pdf'),
(29, 'Physics Class 11 - Chapter 10 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph203.pdf'),
(30, 'Physics Class 11 - Chapter 11 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph204.pdf'),
(31, 'Physics Class 11 - Chapter 12 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph205.pdf'),
(32, 'Physics Class 11 - Chapter 13 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph206.pdf'),
(33, 'Physics Class 11 - Chapter 14 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_11/keph207.pdf'),
(34, 'Physics Class 12 - Chapter 1 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph101.pdf'),
(35, 'Physics Class 12 - Chapter 2 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph102.pdf'),
(36, 'Physics Class 12 - Chapter 3 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph103.pdf'),
(37, 'Physics Class 12 - Chapter 4 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph104.pdf'),
(38, 'Physics Class 12 - Chapter 5 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph105.pdf'),
(39, 'Physics Class 12 - Chapter 6 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph106.pdf'),
(40, 'Physics Class 12 - Chapter 7 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph107.pdf'),
(41, 'Physics Class 12 - Chapter 8 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph108.pdf'),
(42, 'Physics Class 12 - Chapter 9 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph201.pdf'),
(43, 'Physics Class 12 - Chapter 10 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph202.pdf'),
(44, 'Physics Class 12 - Chapter 11 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph203.pdf'),
(45, 'Physics Class 12 - Chapter 12 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph204.pdf'),
(46, 'Physics Class 12 - Chapter 13 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph205.pdf'),
(47, 'Physics Class 12 - Chapter 14 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Physics/Class_12/leph206.pdf'),
(48, 'Biology Class 11 - Chapter 1 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo101.pdf'),
(49, 'Biology Class 11 - Chapter 2 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo102.pdf'),
(50, 'Biology Class 11 - Chapter 3 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo103.pdf'),
(51, 'Biology Class 11 - Chapter 4 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo104.pdf'),
(52, 'Biology Class 11 - Chapter 5 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo105.pdf'),
(53, 'Biology Class 11 - Chapter 6 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo106.pdf'),
(54, 'Biology Class 11 - Chapter 7 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo107.pdf'),
(55, 'Biology Class 11 - Chapter 8 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo108.pdf'),
(56, 'Biology Class 11 - Chapter 9 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo109.pdf'),
(57, 'Biology Class 11 - Chapter 10 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo110.pdf'),
(58, 'Biology Class 11 - Chapter 11 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo111.pdf'),
(59, 'Biology Class 11 - Chapter 12 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo112.pdf'),
(60, 'Biology Class 11 - Chapter 13 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo113.pdf'),
(61, 'Biology Class 11 - Chapter 14 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo114.pdf'),
(62, 'Biology Class 11 - Chapter 15 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo115.pdf'),
(63, 'Biology Class 11 - Chapter 16 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo116.pdf'),
(64, 'Biology Class 11 - Chapter 17 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo117.pdf'),
(65, 'Biology Class 11 - Chapter 18 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo118.pdf'),
(66, 'Biology Class 11 - Chapter 19 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo119.pdf'),
(67, 'Biology Class 12 - Chapter 1 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo101.pdf'),
(68, 'Biology Class 12 - Chapter 2 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo102.pdf'),
(69, 'Biology Class 12 - Chapter 3 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo103.pdf'),
(70, 'Biology Class 12 - Chapter 4 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo104.pdf'),
(71, 'Biology Class 12 - Chapter 5 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo105.pdf'),
(72, 'Biology Class 12 - Chapter 6 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo106.pdf'),
(73, 'Biology Class 12 - Chapter 7 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo107.pdf'),
(74, 'Biology Class 12 - Chapter 8 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo108.pdf'),
(75, 'Biology Class 12 - Chapter 9 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo109.pdf'),
(76, 'Biology Class 12 - Chapter 10 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo110.pdf'),
(77, 'Biology Class 12 - Chapter 11 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo111.pdf'),
(78, 'Biology Class 12 - Chapter 12 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo112.pdf'),
(79, 'Biology Class 12 - Chapter 13 — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_12/lebo113.pdf');

