-- Auto-generated by NEETcoach MCQ Generator
-- 6 questions | 20260516_192953
-- Paste this in: Supabase Dashboard → SQL Editor → New query

INSERT INTO public.questions
  (topic_id, question_text, option_a, option_b, option_c, option_d,
   correct_option, explanation)
VALUES
(1, 'Which of the following best describes the scope of Chemistry as a branch of science?

(A) The study of the physical forces and mechanical energy of matter
(B) The study of the preparation, properties, structure, and reactions of material substances
(C) The study of the classification and evolution of living organisms
(D) The study of the origin and expansion of the universe?', 'The study of the geological composition of the earth and the physical forces shaping its crust', 'The study of the preparation, properties, structure, and reactions of material substances', 'The study of the fundamental physical laws governing the interaction between energy and the motion of matter', 'The study of the physiological processes and evolutionary history of diverse living organisms', 'B', 'Chemistry is defined as the branch of science that studies the preparation, properties, structure, and reactions of material substances.'),
(1, 'In the context of the history of chemistry, the ''Philosopher’s stone'' (Paras) was a legendary substance sought for its purported ability to:

A) Act as a universal solvent for all substances
B) Convert baser metals like iron and copper into gold
C) Produce eternal life through the purification of blood
D) Catalyze the combustion of non-flammable materials?', 'Serve as a medicinal elixir that grants immortality and eternal youth', 'Convert baser metals like iron and copper into gold', 'Act as a universal solvent capable of dissolving all known chemical substances', 'Function as a catalyst to extract pure elements from complex mineral ores', 'B', 'The Philosopher’s stone (Paras) was a legendary substance in early chemical traditions (alchemy) believed to have the power to transmute base metals such as iron and copper into precious gold.'),
(1, 'In the historical context of alchemy and the early development of chemistry, the legendary substance known as the ''Elixir of life'' was primarily sought for its purported ability to:?', 'Convert common metals into pure gold', 'Provide a cure for all diseases', 'Grant immortality to the consumer', 'Function as a universal chemical solvent', 'C', 'Historically, the ''Elixir of life'' was a mythical substance or potion that alchemists believed could grant eternal life or immortality to those who consumed it.'),
(1, 'During the historical period of 1300-1600 CE, the development of chemistry was primarily characterized by which of the following forms?

(A) Metallurgy and Mineralogy
(B) Alchemy and Iatrochemistry
(C) Stoichiometry and Thermodynamics
(D) Electrochemistry and Photochemistry?', 'Metallurgy and Mineralogy', 'Alchemy and Iatrochemistry', 'Stoichiometry and Thermodynamics', 'Electrochemistry and Photochemistry', 'B', 'In the historical timeline of chemical sciences, chemistry developed mainly in the form of Alchemy and Iatrochemistry during the period of 1300-1600 CE.'),
(1, 'Modern chemistry began to take its definitive shape in which of the following periods and regions, following the introduction of alchemical traditions by the Arabs?

(A) 16th century Asia
(B) 18th century Europe
(C) 17th century Europe
(D) 19th century Asia?', '17th century Europe', '18th century Europe', '19th century Europe', '16th century Arabia', 'B', 'According to the historical development of chemical sciences, modern chemistry took shape in 18th century Europe after alchemical traditions were introduced by the Arabs.'),
(1, 'According to the definition provided by Roald Hoffmann, chemistry is best described as the science of:?', 'Elements and their periodic interactions', 'Atoms and their structural arrangements', 'Molecules and their transformations', 'Matter and its physical characteristics', 'C', 'Roald Hoffmann, a Nobel laureate, defined chemistry as the science of molecules and their transformations, highlighting that chemistry deals with the infinite variety of molecules built from elements rather than just the elements themselves.')
ON CONFLICT DO NOTHING;
