-- Auto-generated by NEETcoach MCQ Generator
-- 1 questions | 20260512_165003
-- Paste this in: Supabase Dashboard → SQL Editor → New query

INSERT INTO public.questions
  (topic_id, question_text, option_a, option_b, option_c, option_d,
   correct_option, explanation)
VALUES
(0, '[DRY RUN] What is the main topic of ''Biology is the science of life forms and''?', 'Option A (correct)', 'Option B (wrong)', 'Option C (wrong)', 'Option D (wrong)', 'A', 'This is a dry-run placeholder. No real LLM call was made.')
ON CONFLICT DO NOTHING;
