"""
config.py — Central configuration for the MCQ Generator pipeline.

Loads environment variables and defines the chapter-to-topic mapping
so every NCERT PDF chapter is wired to its Supabase topic slug.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# ── Load .env.local from the repo root (two levels up from this script) ───────
_REPO_ROOT = Path(__file__).resolve().parents[2]  # neet-coach-app/
_ENV_FILE = _REPO_ROOT / ".env.local"

if _ENV_FILE.exists():
    load_dotenv(_ENV_FILE)
else:
    # Fallback: look for a .env in the script directory
    load_dotenv(Path(__file__).parent / ".env")

# ── Required Environment Variables ───────────────────────────────────────────
GEMINI_API_KEY: str = os.environ.get("GEMINI_API_KEY", "")
SUPABASE_URL: str = os.environ.get(
    "SUPABASE_URL",
    os.environ.get("NEXT_PUBLIC_SUPABASE_URL", ""),
)
# Prefer service key (bypasses RLS), fall back to publishable key
SUPABASE_KEY: str = os.environ.get(
    "SUPABASE_SERVICE_KEY",
    os.environ.get("SUPABASE_KEY", ""),
)

# ── LLM Settings ─────────────────────────────────────────────────────────────
LLM_PROVIDER: str = os.environ.get("LLM_PROVIDER", "google")  # "google" or "ollama"
GEMINI_MODEL: str = os.environ.get("GEMINI_MODEL", "gemini-flash-latest")
OLLAMA_MODEL: str = os.environ.get("OLLAMA_MODEL", "gemma4:e4b")
OLLAMA_BASE_URL: str = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
MCQ_PER_CHAPTER: int = int(os.environ.get("MCQ_PER_CHAPTER", "10"))
MAX_RETRIES: int = int(os.environ.get("MAX_RETRIES", "3"))

# ── NCERT Library Path ────────────────────────────────────────────────────────
NCERT_LIBRARY: Path = (
    Path(__file__).resolve().parents[2] / "public" / "pdfs"
)

# ── Chapter Code → Supabase Topic Slug Map ───────────────────────────────────
# Dynamically built to match the slugs generated by migrate_curriculum.py
CHAPTER_TOPIC_MAP: dict[str, str] = {}
_subjects_map = {
    "Physics": "physics",
    "Chemistry": "chemistry",
    "Biology": "biology"
}

if NCERT_LIBRARY.exists():
    for _subject in NCERT_LIBRARY.iterdir():
        if not _subject.is_dir(): continue
        for _class_dir in _subject.iterdir():
            if not _class_dir.is_dir(): continue
            _pdfs = sorted([f.name for f in _class_dir.glob("*.pdf")])
            for _idx, _pdf in enumerate(_pdfs):
                _code = _pdf.replace(".pdf", "")
                _chapter_num = _idx + 1
                if _subject.name == "Biology" and _class_dir.name == "Class_11":
                    bio_11_map = {
                        "kebo101": 1, "kebo102": 2, "kebo103": 3, "kebo104": 4, "kebo105": 5,
                        "kebo106": 6, "kebo107": 7, "kebo108": 8, "kebo109": 9, "kebo110": 10,
                        "kebo111": 13, "kebo112": 14, "kebo113": 15, "kebo114": 17, "kebo115": 18,
                        "kebo116": 19, "kebo117": 20, "kebo118": 21, "kebo119": 22
                    }
                    _chapter_num = bio_11_map.get(_code, _chapter_num)
                _topic_slug = f"{_subjects_map.get(_subject.name, _subject.name.lower())}-{_class_dir.name.lower().replace('_', '-')}-ch-{_chapter_num}"
                CHAPTER_TOPIC_MAP[_code] = _topic_slug


def validate_config() -> None:
    """Raise if critical env vars are missing."""
    missing = []
    if not GEMINI_API_KEY:
        missing.append("GEMINI_API_KEY")
    if not SUPABASE_URL:
        missing.append("SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL)")
    if not SUPABASE_KEY:
        missing.append("SUPABASE_KEY (or SUPABASE_SERVICE_KEY)")
    if missing:
        raise EnvironmentError(
            f"❌ Missing required environment variables: {', '.join(missing)}\n"
            f"   Check .env.local or scripts/mcq_generator/.env.example"
        )
