"""
db_writer.py — Write generated MCQs to Supabase.

Primary:  Supabase Python client (direct API write).
Fallback: Always generates a .sql file for manual import via Supabase SQL Editor.
"""

from __future__ import annotations
import logging
from datetime import datetime
from pathlib import Path

from schemas import MCQRecord

logger = logging.getLogger(__name__)

# ── SQL Fallback Path ─────────────────────────────────────────────────────────
OUTPUT_DIR = Path(__file__).parent / "output"


def _ensure_output_dir() -> Path:
    OUTPUT_DIR.mkdir(exist_ok=True)
    return OUTPUT_DIR


def save_as_sql(mcqs: list[MCQRecord], label: str = "batch") -> Path:
    """
    Write MCQs as a SQL INSERT file that can be pasted into the
    Supabase SQL Editor — works regardless of API auth status.

    Returns:
        Path to the generated .sql file.
    """
    if not mcqs:
        logger.warning("No MCQs to write to SQL.")
        return OUTPUT_DIR / "empty.sql"

    out_dir = _ensure_output_dir()
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    sql_path = out_dir / f"mcqs_{label}_{timestamp}.sql"

    rows = ",\n".join(mcq.to_sql_row() for mcq in mcqs)
    sql = (
        "-- Auto-generated by NEETcoach MCQ Generator\n"
        f"-- {len(mcqs)} questions | {timestamp}\n"
        "-- Paste this in: Supabase Dashboard → SQL Editor → New query\n\n"
        "INSERT INTO public.questions\n"
        "  (topic_id, question_text, option_a, option_b, option_c, option_d,\n"
        "   correct_option, explanation)\n"
        "VALUES\n"
        f"{rows}\n"
        "ON CONFLICT DO NOTHING;\n"
    )

    sql_path.write_text(sql, encoding="utf-8")
    logger.info(f"  💾 SQL saved → {sql_path}")
    return sql_path


def upsert_to_supabase(
    mcqs: list[MCQRecord],
    supabase_url: str,
    supabase_key: str,
    *,
    dry_run: bool = False,
) -> tuple[int, int]:
    """
    Upsert MCQs into public.questions via the Supabase REST API.

    Args:
        mcqs:          List of validated MCQRecord objects.
        supabase_url:  Project URL.
        supabase_key:  Service role key (preferred) or anon key + INSERT policy.
        dry_run:       If True, skip actual write.

    Returns:
        (success_count, skipped_count) tuple.
    """
    if not mcqs:
        return 0, 0

    if dry_run:
        logger.info(f"  🔍 [DRY RUN] Would upsert {len(mcqs)} MCQs")
        return len(mcqs), 0

    try:
        from supabase import create_client, Client  # type: ignore
    except ImportError:
        raise ImportError("Install supabase: pip install supabase")

    client: Client = create_client(supabase_url, supabase_key)

    rows = [
        {
            "topic_id": mcq.topic_id,
            "question_text": mcq.question_text,
            "option_a": mcq.option_a,
            "option_b": mcq.option_b,
            "option_c": mcq.option_c,
            "option_d": mcq.option_d,
            "correct_option": mcq.correct_option,
            "explanation": mcq.explanation,
        }
        for mcq in mcqs
    ]

    success = 0
    skipped = 0

    # Batch in chunks of 50 to stay within Supabase row limits
    BATCH_SIZE = 50
    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        try:
            result = (
                client.table("questions")
                .upsert(batch, on_conflict="question_text,topic_id")
                .execute()
            )
            if result.data:
                success += len(result.data)
            else:
                # Some rows may have been skipped due to conflict
                skipped += len(batch)
        except Exception as e:
            logger.warning(f"  ⚠️  Supabase batch {i // BATCH_SIZE + 1} failed: {e}")
            skipped += len(batch)

    return success, skipped


def write_mcqs(
    mcqs: list[MCQRecord],
    supabase_url: str,
    supabase_key: str,
    label: str = "batch",
    *,
    dry_run: bool = False,
    sql_only: bool = False,
) -> dict:
    """
    Master write function: always saves SQL file + optionally upserts to Supabase.

    Returns:
        Summary dict with counts and file paths.
    """
    # Always generate SQL as backup
    sql_path = save_as_sql(mcqs, label=label)

    db_success = 0
    db_skipped = 0

    if not sql_only and supabase_url and supabase_key:
        try:
            db_success, db_skipped = upsert_to_supabase(
                mcqs, supabase_url, supabase_key, dry_run=dry_run
            )
            if db_success > 0:
                logger.info(f"  ✅ Supabase: {db_success} inserted, {db_skipped} skipped")
        except Exception as e:
            logger.error(f"  ❌ Supabase write failed: {e}")
            logger.info(f"  💡 Use the SQL file instead: {sql_path}")
    else:
        logger.info(f"  ℹ️  SQL-only mode. Import manually: {sql_path}")

    return {
        "total_mcqs": len(mcqs),
        "db_inserted": db_success,
        "db_skipped": db_skipped,
        "sql_file": str(sql_path),
    }
