-- ============================================================
-- SYLLABUS REALIGNMENT & DESCRIPTIVE CHAPTER TITLES
-- Auto-generated migration script
-- ============================================================
BEGIN;

-- Step 1: Realign Biology Class 11 sequential slugs in reverse order
UPDATE public.topics SET slug = 'biology-class-11-ch-22', name = 'Chemical Coordination and Integration', description = 'NCERT Topic for Biology Class 11 — Chemical Coordination and Integration' WHERE slug = 'biology-class-11-ch-19';
UPDATE public.topics SET slug = 'biology-class-11-ch-21', name = 'Neural Control and Coordination', description = 'NCERT Topic for Biology Class 11 — Neural Control and Coordination' WHERE slug = 'biology-class-11-ch-18';
UPDATE public.topics SET slug = 'biology-class-11-ch-20', name = 'Locomotion and Movement', description = 'NCERT Topic for Biology Class 11 — Locomotion and Movement' WHERE slug = 'biology-class-11-ch-17';
UPDATE public.topics SET slug = 'biology-class-11-ch-19', name = 'Excretory Products and their Elimination', description = 'NCERT Topic for Biology Class 11 — Excretory Products and their Elimination' WHERE slug = 'biology-class-11-ch-16';
UPDATE public.topics SET slug = 'biology-class-11-ch-18', name = 'Body Fluids and Circulation', description = 'NCERT Topic for Biology Class 11 — Body Fluids and Circulation' WHERE slug = 'biology-class-11-ch-15';
UPDATE public.topics SET slug = 'biology-class-11-ch-17', name = 'Breathing and Exchange of Gases', description = 'NCERT Topic for Biology Class 11 — Breathing and Exchange of Gases' WHERE slug = 'biology-class-11-ch-14';
UPDATE public.topics SET slug = 'biology-class-11-ch-15', name = 'Plant Growth and Development', description = 'NCERT Topic for Biology Class 11 — Plant Growth and Development' WHERE slug = 'biology-class-11-ch-13';
UPDATE public.topics SET slug = 'biology-class-11-ch-14', name = 'Respiration in Plants', description = 'NCERT Topic for Biology Class 11 — Respiration in Plants' WHERE slug = 'biology-class-11-ch-12';
UPDATE public.topics SET slug = 'biology-class-11-ch-13', name = 'Photosynthesis in Higher Plants', description = 'NCERT Topic for Biology Class 11 — Photosynthesis in Higher Plants' WHERE slug = 'biology-class-11-ch-11';

-- Step 2: Insert missing traditional chapters for Biology Class 11
INSERT INTO public.topics (subject_id, slug, name, description) VALUES ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'biology-class-11-ch-11', 'Transport in Plants', 'NCERT Topic for Biology Class 11 — Transport in Plants') ON CONFLICT (slug) DO UPDATE SET name = 'Transport in Plants';
INSERT INTO public.topics (subject_id, slug, name, description) VALUES ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'biology-class-11-ch-12', 'Mineral Nutrition', 'NCERT Topic for Biology Class 11 — Mineral Nutrition') ON CONFLICT (slug) DO UPDATE SET name = 'Mineral Nutrition';
INSERT INTO public.topics (subject_id, slug, name, description) VALUES ((SELECT id FROM public.subjects WHERE slug = 'biology'), 'biology-class-11-ch-16', 'Digestion and Absorption', 'NCERT Topic for Biology Class 11 — Digestion and Absorption') ON CONFLICT (slug) DO UPDATE SET name = 'Digestion and Absorption';

-- Step 3: Update all topic names and descriptions across all subjects
UPDATE public.topics SET name = 'The Living World', description = 'NCERT Topic for Biology Class 11 — The Living World' WHERE slug = 'biology-class-11-ch-1';
UPDATE public.topics SET name = 'Biological Classification', description = 'NCERT Topic for Biology Class 11 — Biological Classification' WHERE slug = 'biology-class-11-ch-2';
UPDATE public.topics SET name = 'Plant Kingdom', description = 'NCERT Topic for Biology Class 11 — Plant Kingdom' WHERE slug = 'biology-class-11-ch-3';
UPDATE public.topics SET name = 'Animal Kingdom', description = 'NCERT Topic for Biology Class 11 — Animal Kingdom' WHERE slug = 'biology-class-11-ch-4';
UPDATE public.topics SET name = 'Morphology of Flowering Plants', description = 'NCERT Topic for Biology Class 11 — Morphology of Flowering Plants' WHERE slug = 'biology-class-11-ch-5';
UPDATE public.topics SET name = 'Anatomy of Flowering Plants', description = 'NCERT Topic for Biology Class 11 — Anatomy of Flowering Plants' WHERE slug = 'biology-class-11-ch-6';
UPDATE public.topics SET name = 'Structural Organisation in Animals', description = 'NCERT Topic for Biology Class 11 — Structural Organisation in Animals' WHERE slug = 'biology-class-11-ch-7';
UPDATE public.topics SET name = 'Cell: The Unit of Life', description = 'NCERT Topic for Biology Class 11 — Cell: The Unit of Life' WHERE slug = 'biology-class-11-ch-8';
UPDATE public.topics SET name = 'Biomolecules', description = 'NCERT Topic for Biology Class 11 — Biomolecules' WHERE slug = 'biology-class-11-ch-9';
UPDATE public.topics SET name = 'Cell Cycle and Cell Division', description = 'NCERT Topic for Biology Class 11 — Cell Cycle and Cell Division' WHERE slug = 'biology-class-11-ch-10';
UPDATE public.topics SET name = 'Photosynthesis in Higher Plants', description = 'NCERT Topic for Biology Class 11 — Photosynthesis in Higher Plants' WHERE slug = 'biology-class-11-ch-13';
UPDATE public.topics SET name = 'Respiration in Plants', description = 'NCERT Topic for Biology Class 11 — Respiration in Plants' WHERE slug = 'biology-class-11-ch-14';
UPDATE public.topics SET name = 'Plant Growth and Development', description = 'NCERT Topic for Biology Class 11 — Plant Growth and Development' WHERE slug = 'biology-class-11-ch-15';
UPDATE public.topics SET name = 'Breathing and Exchange of Gases', description = 'NCERT Topic for Biology Class 11 — Breathing and Exchange of Gases' WHERE slug = 'biology-class-11-ch-17';
UPDATE public.topics SET name = 'Body Fluids and Circulation', description = 'NCERT Topic for Biology Class 11 — Body Fluids and Circulation' WHERE slug = 'biology-class-11-ch-18';
UPDATE public.topics SET name = 'Excretory Products and their Elimination', description = 'NCERT Topic for Biology Class 11 — Excretory Products and their Elimination' WHERE slug = 'biology-class-11-ch-19';
UPDATE public.topics SET name = 'Locomotion and Movement', description = 'NCERT Topic for Biology Class 11 — Locomotion and Movement' WHERE slug = 'biology-class-11-ch-20';
UPDATE public.topics SET name = 'Neural Control and Coordination', description = 'NCERT Topic for Biology Class 11 — Neural Control and Coordination' WHERE slug = 'biology-class-11-ch-21';
UPDATE public.topics SET name = 'Chemical Coordination and Integration', description = 'NCERT Topic for Biology Class 11 — Chemical Coordination and Integration' WHERE slug = 'biology-class-11-ch-22';
UPDATE public.topics SET name = 'Reproduction in Organisms', description = 'NCERT Topic for Biology Class 12 — Reproduction in Organisms' WHERE slug = 'biology-class-12-ch-1';
UPDATE public.topics SET name = 'Sexual Reproduction in Flowering Plants', description = 'NCERT Topic for Biology Class 12 — Sexual Reproduction in Flowering Plants' WHERE slug = 'biology-class-12-ch-2';
UPDATE public.topics SET name = 'Human Reproduction', description = 'NCERT Topic for Biology Class 12 — Human Reproduction' WHERE slug = 'biology-class-12-ch-3';
UPDATE public.topics SET name = 'Reproductive Health', description = 'NCERT Topic for Biology Class 12 — Reproductive Health' WHERE slug = 'biology-class-12-ch-4';
UPDATE public.topics SET name = 'Principles of Inheritance and Variation', description = 'NCERT Topic for Biology Class 12 — Principles of Inheritance and Variation' WHERE slug = 'biology-class-12-ch-5';
UPDATE public.topics SET name = 'Molecular Basis of Inheritance', description = 'NCERT Topic for Biology Class 12 — Molecular Basis of Inheritance' WHERE slug = 'biology-class-12-ch-6';
UPDATE public.topics SET name = 'Evolution', description = 'NCERT Topic for Biology Class 12 — Evolution' WHERE slug = 'biology-class-12-ch-7';
UPDATE public.topics SET name = 'Human Health and Disease', description = 'NCERT Topic for Biology Class 12 — Human Health and Disease' WHERE slug = 'biology-class-12-ch-8';
UPDATE public.topics SET name = 'Strategies for Enhancement in Food Production', description = 'NCERT Topic for Biology Class 12 — Strategies for Enhancement in Food Production' WHERE slug = 'biology-class-12-ch-9';
UPDATE public.topics SET name = 'Microbes in Human Welfare', description = 'NCERT Topic for Biology Class 12 — Microbes in Human Welfare' WHERE slug = 'biology-class-12-ch-10';
UPDATE public.topics SET name = 'Biotechnology: Principles and Processes', description = 'NCERT Topic for Biology Class 12 — Biotechnology: Principles and Processes' WHERE slug = 'biology-class-12-ch-11';
UPDATE public.topics SET name = 'Biotechnology and its Applications', description = 'NCERT Topic for Biology Class 12 — Biotechnology and its Applications' WHERE slug = 'biology-class-12-ch-12';
UPDATE public.topics SET name = 'Organisms and Populations', description = 'NCERT Topic for Biology Class 12 — Organisms and Populations' WHERE slug = 'biology-class-12-ch-13';
UPDATE public.topics SET name = 'Ecosystem', description = 'NCERT Topic for Biology Class 12 — Ecosystem' WHERE slug = 'biology-class-12-ch-14';
UPDATE public.topics SET name = 'Biodiversity and Conservation', description = 'NCERT Topic for Biology Class 12 — Biodiversity and Conservation' WHERE slug = 'biology-class-12-ch-15';
UPDATE public.topics SET name = 'Environmental Issues', description = 'NCERT Topic for Biology Class 12 — Environmental Issues' WHERE slug = 'biology-class-12-ch-16';
UPDATE public.topics SET name = 'Physical World', description = 'NCERT Topic for Physics Class 11 — Physical World' WHERE slug = 'physics-class-11-ch-1';
UPDATE public.topics SET name = 'Units and Measurements', description = 'NCERT Topic for Physics Class 11 — Units and Measurements' WHERE slug = 'physics-class-11-ch-2';
UPDATE public.topics SET name = 'Motion in a Straight Line', description = 'NCERT Topic for Physics Class 11 — Motion in a Straight Line' WHERE slug = 'physics-class-11-ch-3';
UPDATE public.topics SET name = 'Motion in a Plane', description = 'NCERT Topic for Physics Class 11 — Motion in a Plane' WHERE slug = 'physics-class-11-ch-4';
UPDATE public.topics SET name = 'Laws of Motion', description = 'NCERT Topic for Physics Class 11 — Laws of Motion' WHERE slug = 'physics-class-11-ch-5';
UPDATE public.topics SET name = 'Work, Energy and Power', description = 'NCERT Topic for Physics Class 11 — Work, Energy and Power' WHERE slug = 'physics-class-11-ch-6';
UPDATE public.topics SET name = 'System of Particles and Rotational Motion', description = 'NCERT Topic for Physics Class 11 — System of Particles and Rotational Motion' WHERE slug = 'physics-class-11-ch-7';
UPDATE public.topics SET name = 'Gravitation', description = 'NCERT Topic for Physics Class 11 — Gravitation' WHERE slug = 'physics-class-11-ch-8';
UPDATE public.topics SET name = 'Mechanical Properties of Solids', description = 'NCERT Topic for Physics Class 11 — Mechanical Properties of Solids' WHERE slug = 'physics-class-11-ch-9';
UPDATE public.topics SET name = 'Mechanical Properties of Fluids', description = 'NCERT Topic for Physics Class 11 — Mechanical Properties of Fluids' WHERE slug = 'physics-class-11-ch-10';
UPDATE public.topics SET name = 'Thermal Properties of Matter', description = 'NCERT Topic for Physics Class 11 — Thermal Properties of Matter' WHERE slug = 'physics-class-11-ch-11';
UPDATE public.topics SET name = 'Thermodynamics', description = 'NCERT Topic for Physics Class 11 — Thermodynamics' WHERE slug = 'physics-class-11-ch-12';
UPDATE public.topics SET name = 'Kinetic Theory', description = 'NCERT Topic for Physics Class 11 — Kinetic Theory' WHERE slug = 'physics-class-11-ch-13';
UPDATE public.topics SET name = 'Oscillations', description = 'NCERT Topic for Physics Class 11 — Oscillations' WHERE slug = 'physics-class-11-ch-14';
UPDATE public.topics SET name = 'Waves', description = 'NCERT Topic for Physics Class 11 — Waves' WHERE slug = 'physics-class-11-ch-15';
UPDATE public.topics SET name = 'Electric Charges and Fields', description = 'NCERT Topic for Physics Class 12 — Electric Charges and Fields' WHERE slug = 'physics-class-12-ch-1';
UPDATE public.topics SET name = 'Electrostatic Potential and Capacitance', description = 'NCERT Topic for Physics Class 12 — Electrostatic Potential and Capacitance' WHERE slug = 'physics-class-12-ch-2';
UPDATE public.topics SET name = 'Current Electricity', description = 'NCERT Topic for Physics Class 12 — Current Electricity' WHERE slug = 'physics-class-12-ch-3';
UPDATE public.topics SET name = 'Moving Charges and Magnetism', description = 'NCERT Topic for Physics Class 12 — Moving Charges and Magnetism' WHERE slug = 'physics-class-12-ch-4';
UPDATE public.topics SET name = 'Magnetism and Matter', description = 'NCERT Topic for Physics Class 12 — Magnetism and Matter' WHERE slug = 'physics-class-12-ch-5';
UPDATE public.topics SET name = 'Electromagnetic Induction', description = 'NCERT Topic for Physics Class 12 — Electromagnetic Induction' WHERE slug = 'physics-class-12-ch-6';
UPDATE public.topics SET name = 'Alternating Current', description = 'NCERT Topic for Physics Class 12 — Alternating Current' WHERE slug = 'physics-class-12-ch-7';
UPDATE public.topics SET name = 'Electromagnetic Waves', description = 'NCERT Topic for Physics Class 12 — Electromagnetic Waves' WHERE slug = 'physics-class-12-ch-8';
UPDATE public.topics SET name = 'Ray Optics and Optical Instruments', description = 'NCERT Topic for Physics Class 12 — Ray Optics and Optical Instruments' WHERE slug = 'physics-class-12-ch-9';
UPDATE public.topics SET name = 'Wave Optics', description = 'NCERT Topic for Physics Class 12 — Wave Optics' WHERE slug = 'physics-class-12-ch-10';
UPDATE public.topics SET name = 'Dual Nature of Radiation and Matter', description = 'NCERT Topic for Physics Class 12 — Dual Nature of Radiation and Matter' WHERE slug = 'physics-class-12-ch-11';
UPDATE public.topics SET name = 'Atoms', description = 'NCERT Topic for Physics Class 12 — Atoms' WHERE slug = 'physics-class-12-ch-12';
UPDATE public.topics SET name = 'Nuclei', description = 'NCERT Topic for Physics Class 12 — Nuclei' WHERE slug = 'physics-class-12-ch-13';
UPDATE public.topics SET name = 'Semiconductor Electronics: Materials, Devices and Simple Circuits', description = 'NCERT Topic for Physics Class 12 — Semiconductor Electronics: Materials, Devices and Simple Circuits' WHERE slug = 'physics-class-12-ch-14';
UPDATE public.topics SET name = 'Communication Systems', description = 'NCERT Topic for Physics Class 12 — Communication Systems' WHERE slug = 'physics-class-12-ch-15';
UPDATE public.topics SET name = 'Some Basic Concepts of Chemistry', description = 'NCERT Topic for Chemistry Class 11 — Some Basic Concepts of Chemistry' WHERE slug = 'chemistry-class-11-ch-1';
UPDATE public.topics SET name = 'Structure of Atom', description = 'NCERT Topic for Chemistry Class 11 — Structure of Atom' WHERE slug = 'chemistry-class-11-ch-2';
UPDATE public.topics SET name = 'Classification of Elements and Periodicity in Properties', description = 'NCERT Topic for Chemistry Class 11 — Classification of Elements and Periodicity in Properties' WHERE slug = 'chemistry-class-11-ch-3';
UPDATE public.topics SET name = 'Chemical Bonding and Molecular Structure', description = 'NCERT Topic for Chemistry Class 11 — Chemical Bonding and Molecular Structure' WHERE slug = 'chemistry-class-11-ch-4';
UPDATE public.topics SET name = 'States of Matter', description = 'NCERT Topic for Chemistry Class 11 — States of Matter' WHERE slug = 'chemistry-class-11-ch-5';
UPDATE public.topics SET name = 'Thermodynamics', description = 'NCERT Topic for Chemistry Class 11 — Thermodynamics' WHERE slug = 'chemistry-class-11-ch-6';
UPDATE public.topics SET name = 'Equilibrium', description = 'NCERT Topic for Chemistry Class 11 — Equilibrium' WHERE slug = 'chemistry-class-11-ch-7';
UPDATE public.topics SET name = 'Redox Reactions', description = 'NCERT Topic for Chemistry Class 11 — Redox Reactions' WHERE slug = 'chemistry-class-11-ch-8';
UPDATE public.topics SET name = 'Hydrogen', description = 'NCERT Topic for Chemistry Class 11 — Hydrogen' WHERE slug = 'chemistry-class-11-ch-9';
UPDATE public.topics SET name = 'The s-Block Elements', description = 'NCERT Topic for Chemistry Class 11 — The s-Block Elements' WHERE slug = 'chemistry-class-11-ch-10';
UPDATE public.topics SET name = 'The p-Block Elements', description = 'NCERT Topic for Chemistry Class 11 — The p-Block Elements' WHERE slug = 'chemistry-class-11-ch-11';
UPDATE public.topics SET name = 'Organic Chemistry: Some Basic Principles and Techniques', description = 'NCERT Topic for Chemistry Class 11 — Organic Chemistry: Some Basic Principles and Techniques' WHERE slug = 'chemistry-class-11-ch-12';
UPDATE public.topics SET name = 'Hydrocarbons', description = 'NCERT Topic for Chemistry Class 11 — Hydrocarbons' WHERE slug = 'chemistry-class-11-ch-13';
UPDATE public.topics SET name = 'Environmental Chemistry', description = 'NCERT Topic for Chemistry Class 11 — Environmental Chemistry' WHERE slug = 'chemistry-class-11-ch-14';
UPDATE public.topics SET name = 'The Solid State', description = 'NCERT Topic for Chemistry Class 12 — The Solid State' WHERE slug = 'chemistry-class-12-ch-1';
UPDATE public.topics SET name = 'Solutions', description = 'NCERT Topic for Chemistry Class 12 — Solutions' WHERE slug = 'chemistry-class-12-ch-2';
UPDATE public.topics SET name = 'Electrochemistry', description = 'NCERT Topic for Chemistry Class 12 — Electrochemistry' WHERE slug = 'chemistry-class-12-ch-3';
UPDATE public.topics SET name = 'Chemical Kinetics', description = 'NCERT Topic for Chemistry Class 12 — Chemical Kinetics' WHERE slug = 'chemistry-class-12-ch-4';
UPDATE public.topics SET name = 'Surface Chemistry', description = 'NCERT Topic for Chemistry Class 12 — Surface Chemistry' WHERE slug = 'chemistry-class-12-ch-5';
UPDATE public.topics SET name = 'General Principles and Processes of Isolation of Elements', description = 'NCERT Topic for Chemistry Class 12 — General Principles and Processes of Isolation of Elements' WHERE slug = 'chemistry-class-12-ch-6';
UPDATE public.topics SET name = 'The p-Block Elements', description = 'NCERT Topic for Chemistry Class 12 — The p-Block Elements' WHERE slug = 'chemistry-class-12-ch-7';
UPDATE public.topics SET name = 'The d- and f-Block Elements', description = 'NCERT Topic for Chemistry Class 12 — The d- and f-Block Elements' WHERE slug = 'chemistry-class-12-ch-8';
UPDATE public.topics SET name = 'Coordination Compounds', description = 'NCERT Topic for Chemistry Class 12 — Coordination Compounds' WHERE slug = 'chemistry-class-12-ch-9';
UPDATE public.topics SET name = 'Haloalkanes and Haloarenes', description = 'NCERT Topic for Chemistry Class 12 — Haloalkanes and Haloarenes' WHERE slug = 'chemistry-class-12-ch-10';
UPDATE public.topics SET name = 'Alcohols, Phenols and Ethers', description = 'NCERT Topic for Chemistry Class 12 — Alcohols, Phenols and Ethers' WHERE slug = 'chemistry-class-12-ch-11';
UPDATE public.topics SET name = 'Aldehydes, Ketones and Carboxylic Acids', description = 'NCERT Topic for Chemistry Class 12 — Aldehydes, Ketones and Carboxylic Acids' WHERE slug = 'chemistry-class-12-ch-12';
UPDATE public.topics SET name = 'Amines', description = 'NCERT Topic for Chemistry Class 12 — Amines' WHERE slug = 'chemistry-class-12-ch-13';
UPDATE public.topics SET name = 'Biomolecules', description = 'NCERT Topic for Chemistry Class 12 — Biomolecules' WHERE slug = 'chemistry-class-12-ch-14';
UPDATE public.topics SET name = 'Polymers', description = 'NCERT Topic for Chemistry Class 12 — Polymers' WHERE slug = 'chemistry-class-12-ch-15';
UPDATE public.topics SET name = 'Chemistry in Everyday Life', description = 'NCERT Topic for Chemistry Class 12 — Chemistry in Everyday Life' WHERE slug = 'chemistry-class-12-ch-16';

-- Step 4: Align public.ncert_content titles and pdf_urls
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-1');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-1'), 'The Living World — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo101.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-2');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-2'), 'Biological Classification — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo102.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-3');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-3'), 'Plant Kingdom — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo103.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-4');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-4'), 'Animal Kingdom — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo104.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-5');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-5'), 'Morphology of Flowering Plants — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo105.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-6');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-6'), 'Anatomy of Flowering Plants — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo106.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-7');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-7'), 'Structural Organisation in Animals — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo107.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-8');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-8'), 'Cell: The Unit of Life — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo108.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-9');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-9'), 'Biomolecules — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo109.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-10');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-10'), 'Cell Cycle and Cell Division — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo110.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-11');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-11'), 'Transport in Plants — NCERT PDF', 'NCERT PDF is not available online for this deleted/rationalized chapter. However, MCQ practice remains fully supported.', NULL);
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-12');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-12'), 'Mineral Nutrition — NCERT PDF', 'NCERT PDF is not available online for this deleted/rationalized chapter. However, MCQ practice remains fully supported.', NULL);
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-13');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-13'), 'Photosynthesis in Higher Plants — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo111.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-14');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-14'), 'Respiration in Plants — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo112.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-15');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-15'), 'Plant Growth and Development — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo113.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-16');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-16'), 'Digestion and Absorption — NCERT PDF', 'NCERT PDF is not available online for this deleted/rationalized chapter. However, MCQ practice remains fully supported.', NULL);
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-17');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-17'), 'Breathing and Exchange of Gases — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo114.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-18');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-18'), 'Body Fluids and Circulation — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo115.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-19');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-19'), 'Excretory Products and their Elimination — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo116.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-20');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-20'), 'Locomotion and Movement — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo117.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-21');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-21'), 'Neural Control and Coordination — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo118.pdf');
DELETE FROM public.ncert_content WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-22');
INSERT INTO public.ncert_content (topic_id, title, markdown_body, pdf_url) VALUES ((SELECT id FROM public.topics WHERE slug = 'biology-class-11-ch-22'), 'Chemical Coordination and Integration — NCERT PDF', 'PDF Viewer Only', '/pdfs/Biology/Class_11/kebo119.pdf');
UPDATE public.ncert_content SET title = 'Reproduction in Organisms — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-1');
UPDATE public.ncert_content SET title = 'Sexual Reproduction in Flowering Plants — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-2');
UPDATE public.ncert_content SET title = 'Human Reproduction — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-3');
UPDATE public.ncert_content SET title = 'Reproductive Health — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-4');
UPDATE public.ncert_content SET title = 'Principles of Inheritance and Variation — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-5');
UPDATE public.ncert_content SET title = 'Molecular Basis of Inheritance — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-6');
UPDATE public.ncert_content SET title = 'Evolution — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-7');
UPDATE public.ncert_content SET title = 'Human Health and Disease — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-8');
UPDATE public.ncert_content SET title = 'Strategies for Enhancement in Food Production — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-9');
UPDATE public.ncert_content SET title = 'Microbes in Human Welfare — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-10');
UPDATE public.ncert_content SET title = 'Biotechnology: Principles and Processes — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-11');
UPDATE public.ncert_content SET title = 'Biotechnology and its Applications — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-12');
UPDATE public.ncert_content SET title = 'Organisms and Populations — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-13');
UPDATE public.ncert_content SET title = 'Ecosystem — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-14');
UPDATE public.ncert_content SET title = 'Biodiversity and Conservation — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-15');
UPDATE public.ncert_content SET title = 'Environmental Issues — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'biology-class-12-ch-16');
UPDATE public.ncert_content SET title = 'Physical World — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-1');
UPDATE public.ncert_content SET title = 'Units and Measurements — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-2');
UPDATE public.ncert_content SET title = 'Motion in a Straight Line — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-3');
UPDATE public.ncert_content SET title = 'Motion in a Plane — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-4');
UPDATE public.ncert_content SET title = 'Laws of Motion — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-5');
UPDATE public.ncert_content SET title = 'Work, Energy and Power — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-6');
UPDATE public.ncert_content SET title = 'System of Particles and Rotational Motion — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-7');
UPDATE public.ncert_content SET title = 'Gravitation — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-8');
UPDATE public.ncert_content SET title = 'Mechanical Properties of Solids — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-9');
UPDATE public.ncert_content SET title = 'Mechanical Properties of Fluids — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-10');
UPDATE public.ncert_content SET title = 'Thermal Properties of Matter — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-11');
UPDATE public.ncert_content SET title = 'Thermodynamics — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-12');
UPDATE public.ncert_content SET title = 'Kinetic Theory — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-13');
UPDATE public.ncert_content SET title = 'Oscillations — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-14');
UPDATE public.ncert_content SET title = 'Waves — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-11-ch-15');
UPDATE public.ncert_content SET title = 'Electric Charges and Fields — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-1');
UPDATE public.ncert_content SET title = 'Electrostatic Potential and Capacitance — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-2');
UPDATE public.ncert_content SET title = 'Current Electricity — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-3');
UPDATE public.ncert_content SET title = 'Moving Charges and Magnetism — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-4');
UPDATE public.ncert_content SET title = 'Magnetism and Matter — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-5');
UPDATE public.ncert_content SET title = 'Electromagnetic Induction — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-6');
UPDATE public.ncert_content SET title = 'Alternating Current — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-7');
UPDATE public.ncert_content SET title = 'Electromagnetic Waves — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-8');
UPDATE public.ncert_content SET title = 'Ray Optics and Optical Instruments — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-9');
UPDATE public.ncert_content SET title = 'Wave Optics — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-10');
UPDATE public.ncert_content SET title = 'Dual Nature of Radiation and Matter — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-11');
UPDATE public.ncert_content SET title = 'Atoms — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-12');
UPDATE public.ncert_content SET title = 'Nuclei — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-13');
UPDATE public.ncert_content SET title = 'Semiconductor Electronics: Materials, Devices and Simple Circuits — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-14');
UPDATE public.ncert_content SET title = 'Communication Systems — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'physics-class-12-ch-15');
UPDATE public.ncert_content SET title = 'Some Basic Concepts of Chemistry — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-1');
UPDATE public.ncert_content SET title = 'Structure of Atom — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-2');
UPDATE public.ncert_content SET title = 'Classification of Elements and Periodicity in Properties — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-3');
UPDATE public.ncert_content SET title = 'Chemical Bonding and Molecular Structure — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-4');
UPDATE public.ncert_content SET title = 'States of Matter — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-5');
UPDATE public.ncert_content SET title = 'Thermodynamics — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-6');
UPDATE public.ncert_content SET title = 'Equilibrium — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-7');
UPDATE public.ncert_content SET title = 'Redox Reactions — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-8');
UPDATE public.ncert_content SET title = 'Hydrogen — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-9');
UPDATE public.ncert_content SET title = 'The s-Block Elements — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-10');
UPDATE public.ncert_content SET title = 'The p-Block Elements — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-11');
UPDATE public.ncert_content SET title = 'Organic Chemistry: Some Basic Principles and Techniques — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-12');
UPDATE public.ncert_content SET title = 'Hydrocarbons — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-13');
UPDATE public.ncert_content SET title = 'Environmental Chemistry — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-11-ch-14');
UPDATE public.ncert_content SET title = 'The Solid State — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-1');
UPDATE public.ncert_content SET title = 'Solutions — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-2');
UPDATE public.ncert_content SET title = 'Electrochemistry — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-3');
UPDATE public.ncert_content SET title = 'Chemical Kinetics — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-4');
UPDATE public.ncert_content SET title = 'Surface Chemistry — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-5');
UPDATE public.ncert_content SET title = 'General Principles and Processes of Isolation of Elements — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-6');
UPDATE public.ncert_content SET title = 'The p-Block Elements — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-7');
UPDATE public.ncert_content SET title = 'The d- and f-Block Elements — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-8');
UPDATE public.ncert_content SET title = 'Coordination Compounds — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-9');
UPDATE public.ncert_content SET title = 'Haloalkanes and Haloarenes — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-10');
UPDATE public.ncert_content SET title = 'Alcohols, Phenols and Ethers — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-11');
UPDATE public.ncert_content SET title = 'Aldehydes, Ketones and Carboxylic Acids — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-12');
UPDATE public.ncert_content SET title = 'Amines — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-13');
UPDATE public.ncert_content SET title = 'Biomolecules — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-14');
UPDATE public.ncert_content SET title = 'Polymers — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-15');
UPDATE public.ncert_content SET title = 'Chemistry in Everyday Life — NCERT PDF' WHERE topic_id = (SELECT id FROM public.topics WHERE slug = 'chemistry-class-12-ch-16');
COMMIT;